version: "3.3"
services:
  catering_service:
    build: .
    ports:
    - "8000:80"
    depends_on:
      - db
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_DB: catering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: faridun
    volumes:
      - db_data:/var/lib/postgresql/data
  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@mail.ru
      PGADMIN_DEFAULT_PASSWORD: faridun
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data: